services:
  prometheus:
    image: prom/prometheus:latest
    container_name: cloud-advisory-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: cloud-advisory-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus